version: 2.1
orbs:
  newman: newman/newman-run
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./mrx_api.collection.postman_collection.json
workflows: null
